version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
