version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_redis_password  # 🔴 Change this if needed
    command: redis-server --requirepass your_redis_password # 🔴 Change password

  mongodb:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_mongo_username  # 🔴 Change username
      - MONGO_INITDB_ROOT_PASSWORD=your_mongo_password  # 🔴 Change password
